server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#      - id: HIGH-SCHOOL-SERVICE
#        uri: lb://HIGH-SCHOOL-SERVICE
#        predicates:
#          - Path=/highschools/**
#          - Header=highSchoolsToken,highSchoolsTokenValue
#      - id: PROGRAM-SERVICE
#        uri: lb://PROGRAM-SERVICE
#        predicates:
#          - Path=/programs/**
#          - Header=programsToken,programsTokenValue

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
     hostname: localhost
